### ISSUE TITLE
Compatability with Authoring tool

### ISSUE THREAD

**Issue by hmaffin** [cgkineo/adapt-devtools#11]
Is uploadable to AT ok - can enable it but cog icon never appears on page. Is there anything else that needs turning on or being present in the course to make it work? I was just testing it on a simple one page course, and added an MCQ.

**Comment by moloko** [comment]
can you attach your config.json so we can have a look?

**Comment by hmaffin** [comment]
{
  "_id": "56fcfa5ac1b586c010a1dd45",
  "_courseId": "56fcfa59c1b586c010a1dd44",
  "_drawer": {
    "_showEasing": "easeOutQuart",
    "_hideEasing": "easeInQuart",
    "_duration": 400
  },
  "_accessibility": {
    "_isEnabled": false,
    "_shouldSupportLegacyBrowsers": true,
    "_isTextProcessorEnabled": false
  },
  "screenSize": {
    "small": 519,
    "medium": 759,
    "large": 1024
  },
  "__v": 0,
  "_generateSourcemap": false,
  "_questionWeight": 1,
  "_defaultDirection": "ltr",
  "_defaultLanguage": "en",
  "_devtools": {
    "_isEnabled": null
  },
  "build": {
    "includes": [
      "adapt-contrib-vanilla",
      "adapt-contrib-boxMenu",
      "adapt-devtools",
      "adapt-contrib-resources",
      "adapt-narrativeStrip",
      "adapt-contrib-mcq"
    ]
  }
}

**Comment by hmaffin** [comment]
I would suggest 

"_devtools": {
"_isEnabled": null
},

is to blame :)

**Comment by moloko** [comment]
yep I would agree with that! And you've definitely set "Enable dev tools" to 'true' in the extension settings?

**Comment by hmaffin** [comment]
Have gone into the Manage Extensions part of the course, and clicked Add so it goes up to the enabled extensions part. Is there more to do than that?

**Comment by hmaffin** [comment]
OK so solution to this is to make sure you're not a doofus - and turn it on after you have enabled it for the project.

**Comment by hmaffin** [comment]
OK so solution to this is to make sure you're not a doofus - and turn it on after you have enabled it for the project.

**Comment by moloko** [comment]
I think we should probably set `_isEnabled` as a required property anyway... though as the default is probably best set to `false` it wouldn't have helped you in this instance!!
