### ISSUE TITLE
Add option to complete all objects in the PLP

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-devtools#12]
Would be easier for devs and tester on the page. This was a feature of the kcheat extension.

**Comment by moloko** [comment]
+1

**Comment by chris-steele** [comment]
Yep this is something I've had on my list for a while. It'd be nice it pass/fail/half only targetted questions and there was a separate control to complete components.

+1

**Comment by chris-steele** [comment]
Going to make a start on this now - finally!

**Comment by chris-steele** [comment]
Guys, if you have chance, can you take a look at https://github.com/chris-steele/adapt-devtools-demo to see if the new pass/half/fail and complete page approach works for you.
