### ISSUE TITLE
incorporate tota11y

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-devtools#13]
Chris, love the DevTools! Thanks.

I tripped across tota11y and think it's a great tool. 
web: http://khan.github.io/tota11y/#Try-it 
code: https://github.com/Khan/tota11y 
Thought it might make a nice addition. 

Note this issue, though: https://github.com/Khan/tota11y/issues/85 Seems there are a couple of ways to proceed, but it was burning up too much of my Saturday afternoon to continue.

**Comment by hmaffin** [comment]
Wow that's a really useful tool! Well spotted Chuck!

**Comment by oliverfoster** [comment]
+1

**Comment by chris-steele** [comment]
Hi Chuck, yes this looks very interesting! I'll try to find some time to look into incorporating it. I'll see if I can work around the bug - seems like a namespace problem for sure.

**Comment by chris-steele** [comment]
I've had a go at integrating this, but had no luck defeating the compatibility bug with requireJS. I'll keep an eye on tota11y for updates.
