### ISSUE TITLE
devtools - "_lockType": "lockLast" support

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-devtools#15]
Please can you add in support for "_lockType": "lockLast" into the 'Unlock Menu' option within the devtools extension.

**Comment by chris-steele** [comment]
In progress

**Comment by chris-steele** [comment]
Done - I've applied to ken15223. At the moment the changes are just in develop, will push to master with a host of other stuff shortly. Let me know what you think @guywillis. Cheers.

**Comment by guywillis** [comment]
Works perfectly! Thanks Chris.

**Comment by chris-steele** [comment]
Awesome. The _lockType property can be used on any element that has children (course, content object, article, block) so the unlock feature will handle all cases.
