### ISSUE TITLE
Version 2.1.6 still has old version in bower

### ISSUE THREAD

**Issue by hmaffin** [cgkineo/adapt-devtools#17]
bower.json needs to be upped to 2.1.6 for the latest release!

**Comment by chris-steele** [comment]
Ah, was this the version number? Should be resolved now with v2.1.7. Thanks!

**Comment by hmaffin** [comment]
Yep - I managed to update to 2.1.7 now :) Thanks!

**Comment by chris-steele** [comment]
Awesome, sorry for taking so long to respond!
