### ISSUE TITLE
problem with auto-answering questions

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#18]
in m20 of uk-lcel-403243 I only seem to be able to CTRL+click submit to auto-answer question c-270, for some reason it doesn't work for any of the other questions on this page (which are a mixture of Matching and MCQ).

**Comment by moloko** [comment]
My bad... totally failed to spot that the majority of question components on this page have NO correct answer!

If it's possible, logging something like "no correct options to select for component _id_" to the console would be helpful

**Comment by chris-steele** [comment]
@moloko thanks for the heads up on this. Auto answer and pass/half/fail will now select options in (g)mcq and matching components if there is no correct response.
