### ISSUE TITLE
course map not working with latest version of the framework

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#21]
source: https://community.adaptlearning.org/mod/forum/discuss.php?d=2389

The Kineo adapt-devtools extension is a very useful tool, that makes it easier to develop and test Adapt courses.

But something seems to be broken after the latest framework update.
It seems that the "jquery.js" file referenced in the "assets/map.html" file is the problem (it cannot be loaded).

I suspect that the problem is that the framework, after dropping IE8 support, is using jquery v2.
I tried changing the line:

`<script type="text/javascript" src="../libraries/jquery.js"></script>`

to:

`<script type="text/javascript" src="../libraries/jquery.v2.min.js"></script>`

and that seemed to do the trick - but that is just me hacking, and I am not sure if there is anything else that needs to be changed (or it needs to be fixed in another way).

**Comment by chris-steele** [comment]
@moloko forgot you'd created an actual issue for this. I've got a [workaround](https://github.com/cgkineo/adapt-devtools/commit/b5866f512539d2f4efc12efbabfd4dc89f100b4c) for the path problem by looking at the requirejs config of Adapt. If that fails (which it shouldn't ever) then it falls back to trying a hard path to jQuery.v2.min.js.

**Comment by chris-steele** [comment]
Resolved by 3859f6c56be50f2588d3b4868651dc3f23712454
