### ISSUE TITLE
Not compatible with adapt-contrib-matching v2.2.1

### ISSUE THREAD

**Issue by chris-steele** [cgkineo/adapt-devtools#31]
To-do: adjust code to use select2 API to get/set selected options.

**Comment by moloko** [comment]
before you spend too much time on this... https://github.com/adaptlearning/adapt-contrib-matching/pull/116

**Comment by chris-steele** [comment]
Fixed in https://github.com/cgkineo/adapt-devtools/commit/b031049d20c36b8cdf93aec2a262ef1d8b8913b7
