### ISSUE TITLE
needs updating to work with Matching v3

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#33]
just noticed that ctrl-click submit doesn't work, I'm guessing because of the recent re-write of the matching component

annoying as this is the question component that I use this feature on most of all!

**Comment by chris-steele** [comment]
Fixed in https://github.com/cgkineo/adapt-devtools/commit/9df8bb5fe21452ffc91785690c5b436da9a4414b

**Comment by moloko** [comment]
thanks @chris-steele confirmed this is working for me now
