### ISSUE TITLE
needs updating to work with text input v3

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#34]
ctrl-clicking submit inputs the correct answer but doesn't submit it; clicking submit has no effect unless you then make some kind of amend to the text

**Comment by chris-steele** [comment]
Fixed in https://github.com/cgkineo/adapt-devtools/commit/a3f4756f0172f15c10e46313df4215996c6ec3c4

**Comment by moloko** [comment]
thanks @chris-steele confirmed this is working for me now
