### ISSUE TITLE
needs updating to work with ItemsQuestionModel

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#35]
for question components that have been updated to use `ItemsQuestionModel` you now have to look up the answer in the `_children.models` array in order for it to be able to select the right answer when `_isRandom: true`:
![image](https://user-images.githubusercontent.com/1249597/58957091-cc5d7880-8797-11e9-92ef-46bf2ea23ba7.png)

**Comment by tomgreenfield** [comment]
👍  `view.model.get('_items')` → `view.model.getChildren()`

**Comment by chris-steele** [comment]
Fixed in https://github.com/cgkineo/adapt-devtools/commit/9df8bb5fe21452ffc91785690c5b436da9a4414b

**Comment by moloko** [comment]
thanks @chris-steele confirmed this is working for me now
