### ISSUE TITLE
Pass/Half/Fail not functioning correctly if MCQ options are randomized.

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-devtools#36]
It seems to think that the order in which "_shouldBeSelected" is set within the JSON are the correct/incorrect answers. Not after the options are randomized.

**Comment by moloko** [comment]
@joe-replin this is working fine for me using:
* Adapt v4.2.0
* devtools v2.1.24
* MCQ v3.0.0
* assessment v3.1.0

Are you definitely using the latest version of devtools? There were some pretty big updates ([this in particular](https://github.com/cgkineo/adapt-devtools/issues/35)) to this recently... If you were and it's still not working, please could you supply more details?

**Comment by joe-replin** [comment]
Great recommendation Matt, thank you. My dev tools version was 2 releases behind. Will remember to check the logs in the future!
