### ISSUE TITLE
Grunt build failing with legacy framework

### ISSUE THREAD

**Issue by tomgreenfield** [cgkineo/adapt-devtools#38]
The following line, added for version 2.1.23, is breaking builds using the legacy framework:
https://github.com/cgkineo/adapt-devtools/blob/a3f4756f0172f15c10e46313df4215996c6ec3c4/js/auto-answer.js#L4
```console
Fatal error: Error: ENOENT: no such file or directory, open '/adapt_framework/src/core/js/models/itemsQuestionModel.js'
In module tree:
     core/js/app
       extensions/adapt-devtools/js/adapt-devtools
         extensions/adapt-devtools/js/pass-half-fail
           extensions/adapt-devtools/js/auto-answer
```

Please could this be patched to be backwards compatible as this is breaking legacy authoring tool instances which have Developer Tools 2.1.23 or higher installed.

**Comment by oliverfoster** [comment]
You can fetch modules dynamically at run-time and fail silently:

Async:
```js
  var ItemsQuestionModel;
  require([
    'core/js/models/itemsQuestionModel'
  ], function(a) {
    // get module if available
    ItemsQuestionModel = a;
  }, function() {
    // fail silently if unavailable, leaving the variable undefined
  });
```

Sync:
```js
  var ItemsQuestionModel;
  try {
    // get module if available
    ItemsQuestionModel = require('core/js/models/itemsQuestionModel');
  } catch (e) {
  // fail silently if unavailable, leaving the variable undefined
  }
```

**Comment by chris-steele** [comment]
Fixed in https://github.com/cgkineo/adapt-devtools/commit/04d6c1c90b5f86d371aa9963cdfd113de67ca66c

**Comment by chris-steele** [comment]
Just seeing your suggested fix now, sorry :open_mouth:  You're too quick :smile:
