### ISSUE TITLE
JavaScript error when using 'unlock' function of devtools

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#46]
in Adapt v5.6.1 with devtools v3.0.2, if I try to use the 'unlock' function on a step-locked course menu, I get a JavaScript error and the course will not (re)load.

In FF:
![image](https://user-images.githubusercontent.com/1249597/88406821-1bfe6980-cdc9-11ea-8b94-367ca2be013f.png)

Chrome:
![image](https://user-images.githubusercontent.com/1249597/88406854-27519500-cdc9-11ea-887e-4abad2e97b89.png)

IE11:
![image](https://user-images.githubusercontent.com/1249597/88406894-35071a80-cdc9-11ea-969a-bf32967b361c.png)

**Comment by chris-steele** [comment]
Fix for this pending at https://github.com/adaptlearning/adapt_framework/pull/2852

**Comment by chris-steele** [comment]
Fixed by https://github.com/adaptlearning/adapt_framework/commit/bc99582758f310a05fc9f20936d508f0e18cc0d8
