### ISSUE TITLE
'unlock' error leaves course hanging

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-devtools#47]
I've noticed this on a couple of v5 projects now. Using 'unlock' to unlock menu items throws an error and leaves the course hanging on the load screen.

Console is logging the following:
`jquery.min.js:2 Uncaught (in promise) TypeError: Cannot read property 'defaultView' of undefined`

As a work around, I'm using 'complete menu' instead and going into the first topic. On return to the menu all the menu items are unlocked.

**Comment by moloko** [comment]
@kirsty-hames sounds like #46 to me

**Comment by moloko** [comment]
if so, this should fix it https://github.com/adaptlearning/adapt_framework/pull/2852/files

**Comment by kirsty-hames** [comment]
Fix worked thanks @moloko
