### ISSUE TITLE
compatibility with Adapt FW v5.8.0

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-devtools#48]
The new 'rollup' module bundler in Adapt v5.8.0 is not happy with this extension! I think it's either the references to `coreJS` or the old `define(function(require){})` module definitions

**Comment by oliverfoster** [comment]
Both should be fine. `coreJS` definitely still gets mapped. More likely the commonjs style definitions. I'll try to fix in adapt and let you know.

**Comment by chris-steele** [comment]
My first impression is just that there are loads of `require()` calls. Is there any function mapping now that require has been dropped?

**Comment by oliverfoster** [comment]
Yes, but it's not working correctly. It's leaving `var ;` in place where it shouldn't.

**Comment by oliverfoster** [comment]
Try this: https://github.com/adaptlearning/adapt_framework/pull/2998

**Comment by moloko** [comment]
FW v5.8.1 fixes this issue - but now I can get past that I'm getting a different issue! See #49
