### ISSUE TITLE
Not an issue?

### ISSUE THREAD

**Issue by hmaffin** [cgkineo/adapt-devtools#5]
Not an issue just a comment - this looks AMAZING!

**Comment by moloko** [comment]
haha thanks for this @chris-steele will be pleased! it is really helpful, I think #4 will make it even better

**Comment by chris-steele** [comment]
I am indeed pleased, that is great to hear :) Hopefully I will implement #4 and a few other tweaks soon!

**Comment by hmaffin** [comment]
Do you know what would be greater-er? Authoring Tool compatability ;)

**Comment by moloko** [comment]
good idea! will do that now

**Comment by hmaffin** [comment]
Hehehe bless your little cotton socks.

**Comment by moloko** [comment]
OK all done, let me know how you get on

**Comment by hmaffin** [comment]
Installed fine just now - previewing course to try it!

**Comment by hmaffin** [comment]
Don't see a cog icon, even on a page with questions on it. Are there pre-requisites of the course for it to appear?

**Comment by moloko** [comment]
other than enabling it in the config and having an up-to-date version of trickle, I don't think so

**Comment by hmaffin** [comment]
ah - might have forgotten to .... enable.... it *cough cough*

**Comment by moloko** [comment]
oooh one cone of shame for @hmaffin please

**Comment by hmaffin** [comment]
Great!, i'll add it to the rest of collection....

**Comment by hmaffin** [comment]
Enabled but still no cog. Do I need Trickle enabled too? I turned it off for this course...

**Comment by moloko** [comment]
no trickle definitely not required

I'll give it a test on the out-of-the-box framework shortly

**Comment by hmaffin** [comment]
More likely to be me than you mate. No rush :D

**Comment by moloko** [comment]
OK well it works for me on the out-of-the-box framework (building via the CLI)

maybe send me your config.json as it's possible I've not set properties.schema up correctly?

**Comment by hmaffin** [comment]
There's a few - which one do you want? :)

**Comment by moloko** [comment]
any that include the adapt-cheat plugin where it's enabled but not working in the output

**Comment by hmaffin** [comment]
THis right?
[config - Copy.txt](https://github.com/cgkineo/adapt-cheat/files/126242/config.-.Copy.txt)

**Comment by moloko** [comment]
well that doesn't have a `_cheat` entry in it - so one of us is doing something wrong

**Comment by hmaffin** [comment]
I used Brackets to search for "cheat" in my project and found it in the adapt.css if that helps :)

**Comment by moloko** [comment]
well assuming you definitely enabled it in the settings for this project then it's likely to be something wrong on my side, I'll see about getting Tom T to have a look as he knows more about the AT than I do

**Comment by hmaffin** [comment]
Ah bless you. I was only able to add it at Manage Extensions level - I couldn't see any sign of it in the Course settings...

**Comment by taylortom** [comment]
Sorry for the delay, [this](https://github.com/cgkineo/adapt-cheat/pull/6) should fix it!

**Comment by taylortom** [comment]
Actually doesn't fix it :D

Extensions at config-level seem to be nested in an extensions object:
```
...rest of config.json...
"_extensions": {
    "_cheat": {
      "_isEnabled": true
    }
  },
```
So the extension's never [initialised](https://github.com/cgkineo/adapt-cheat/blob/master/js/adapt-cheat.js#L224-L236)

**Comment by moloko** [comment]
@taylortom that's odd, how come we don't get the same issue with contrib-spoor?

**Comment by taylortom** [comment]
https://github.com/cgkineo/adapt-cheat/pull/7

@moloko looking through the extensions, the problem seems to be consistency. It looks as though none of the extensions (that I tried, at least) have settings in `config.json`. Spoor...I'm just testing now.

**Comment by taylortom** [comment]
I think spoor might be broken

**Comment by moloko** [comment]
contrib-trickle has one that can optionally go into config.json - but I've never tried setting that via the AT

**Comment by hmaffin** [comment]
OK so it went from being a compliment to a lot of work for you guys but at least some knowledge came out of it?! *grin*

**Comment by taylortom** [comment]
Well we found out that spoor is broken :grin: 

Actually, when's the last time you tested an AT-developed course with spoor?

**Comment by chris-steele** [comment]
Thanks guys for looking into the AT stuff. And good luck - we're all counting on you.

**Comment by hmaffin** [comment]
I publish all my courses with Spoor for Moodle - does that count?

**Comment by moloko** [comment]
@chris-steele an Airplane! reference? Surely you can't be serious...

**Comment by chris-steele** [comment]
@moloko Fix this one for the Zipper...

**Comment by chris-steele** [comment]
@taylortom what's the status of this buddy?

**Comment by taylortom** [comment]
It's working for me (i.e. this https://github.com/cgkineo/adapt-cheat/issues/5#issuecomment-182948328).

@hmaffin?

**Comment by chris-steele** [comment]
@taylortom we've had a name change so the targetAttribute has become _devtools - is that OK or does it need any action from the AT side?

**Comment by taylortom** [comment]
@chris-steele should just need the `bower.json` updated, so looks good to me

**Comment by chris-steele** [comment]
Great thanks, I reckon we can close this one now then!
