### ISSUE TITLE
keypress interference with glossary search

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-devtools#54]
The keypresses added in https://github.com/cgkineo/adapt-devtools/commit/48f887dc48b5ba14251e280c635d6775704b322f cause the drawer to close if you use any of these keys within the search facility of the glossary.

Obviously shouldn't be an issue for end users as devtools should be disabled/excluded in client deliveries, but something that should probably be resolved. Do we really need the keypress shortcuts?

**Comment by chris-steele** [comment]
Fixed by https://github.com/cgkineo/adapt-devtools/commit/d1599deea72948f64437ff4247ccceb11cafd600
