### ISSUE TITLE
"Unlock" also untrickles

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-devtools#69]
### Subject of the issue
Clicking the "unlock" button also untrickles everything in addition to unlocking topics on the menu.

### Your environment
* AAT (legacy)
* Also tested directly in the Framework v5.31.6
* Dev Tools 3.0.22

### Steps to reproduce

1. Set up a course to use sequential locking
2. On the 2nd page, add some blocks with Trickles.
3. Preview the course and use the unlock option

### Result
Trickles are unlocked in addition to content objects.

**Comment by oliverfoster** [comment]
Trickle is a locking mechanism

**Comment by swashbuck** [comment]
> Trickle is a locking mechanism

@oliverfoster That is true! I may be thinking of older behavior where Unlock only unlocked the content objects and did not affect Trickle. From the docs:

> Once selected adapt-devtools will disable Adapt core locking (>=v2.0.9) throughout the course. For courses using **older** versions of the Adapt framework this feature will only attempt to break locking on menus, e.g. linear step-locking, assessment locking etc.

I would argue that it's useful to still have it work this way. A common use case:

- The course contains 10 topics
- Sequential locking is enabled and some topics utilize Trickle
- A QA reviewer wants to review topic 8 to see if Trickles are properly applied. Because of how Unlock works now, they would need to manually complete topics 1 through 7 to see the Trickles in topic 8.
