### ISSUE TITLE
Dev Tools blocks Inspector

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-devtools#71]
### Subject of the issue
If both Dev Tools and Inspector ([adapt-inspector](https://github.com/cgkineo/adapt-inspector)) are enabled, Inspector no longer works. I am not sure if this is an issue with Dev Tools or Inspector.

May be related to #72 

### Your environment
* Framework 5.31.11
* Dev Tools 3.1.0
* Inspector 1.0.1

### Steps to reproduce
Add the following to _config.json_:

```
  "_devtools": {
    "_isEnabled": true
  },
  "_inspector": {
    "_isEnabled": true
  },
```

### Expected behaviour
Both Dev Tools and Inspector should be enabled

### Actual behaviour
Inspector is not enabled. Hover outlines are not visible.

**Comment by oliverfoster** [comment]
Fixed in https://github.com/cgkineo/adapt-devtools/releases/tag/v3.2.2
