### ISSUE TITLE
dev.json error

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-devtools#74]
### Subject of the issue/enhancement/features
What is this error I see in our courses with devtools? It appears whether or not I have devtools enabled in my project. If I add a blank dev.json file to the root of my build, the error goes away.

Should a dev.json file exist within a 'required' folder?
Did the dev.json file serve a purpose in a previous version?

### Your environment
* devtools - 3.0.20
* adapt - 5.30.3

### Steps to reproduce
Add devtools to any build and check console.

### Expected behaviour
I shouldn't expect to see an error message in my builds, even if devtools is disabled.

### Screenshots (if you can)
![image](https://github.com/cgkineo/adapt-devtools/assets/7740674/b2b1ad94-2336-4316-9bbc-8aa0854ca20e)

**Comment by swashbuck** [comment]
@chris-steele Is the _dev.json_ file used anymore? It seems it exists as a way to specify models that should be excluded?

If this is still needed, I can look into making this a warning rather than an error message.
