### ISSUE TITLE
Change the way window.Adapt is added

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-devtools#78]
### Subject of the issue
[Dev Tools exposes an `Adapt` variable that references `core/js/adapt`.](https://github.com/cgkineo/adapt-devtools/blob/8225a6f99191644da9e23de10fa71ecf5b47d84b/js/utils.js#L74) This is useful for debugging. However, on several occasions, course bugs were not found until final release to the client where Dev Tools is disabled. This obviously makes us look bad to the client.

Ideally, when QA does their final check of the final release, they would look for any errors in the web developer console. Also, in an ideal world, developers would remember to always import the Adapt variable. However, this doesn't always happen in reality.

I would like to see a configuration option to disable the exposed `Adapt` variable.

### Steps to reproduce
1. In a plugin, reference `Adapt` _without_ first importing it with `import Adapt from 'core/js/adapt';`

```
const ariaLabels = Adapt.course.get('_globals')._accessibility._ariaLabels;
```
2. Enable Dev Tools and test the course.
3. Disable Dev Tools and test the course.

### Expected behaviour
No console errors.

### Actual behaviour
Console errors during step 3.

```
ReferenceError: Adapt is not defined
```

**Comment by swashbuck** [comment]
Is there a way to only expose the `Adapt` variable to CLI and _not_ to plugins that may abuse it?

**Comment by oliverfoster** [comment]
The Adapt singleton should never be exposed like this really, for the reasons you've just mentioned, in that it becomes a temporary and confusing global which is subsequently removed when the plugin is removed. Also, the Adapt singleton isn't an API for external applications to use.

An alternative for debugging is to use the phrase `require('core/js/adapt')` in the console to return the `Adapt` singleton.

If you're developing plugins you should be following the [git flow](https://github.com/adaptlearning/adapt_framework/wiki/Git-flow) and eslint should be working and it will definitely tell you that you're missing an import with a giant red squiggly:
![image](https://github.com/cgkineo/adapt-devtools/assets/7974663/461918be-95b4-4c1a-b4c0-0af4186787b1)

> Also, in an ideal world, developers would remember to always import the Adapt variable. However, this doesn't always happen in reality.

It should always happen. Not including an import or not noticing the eslint isn't working or not developing a plugin in a way that allows eslint to work is a little unacceptable. Those tools are there for a reason.

As there always has been a reasonable alternative to exposing the `window.Adapt` in `require('core/js/adapt')` may I suggest that we just remove this code entirely? 

https://github.com/cgkineo/adapt-devtools/blob/8225a6f99191644da9e23de10fa71ecf5b47d84b/js/utils.js#L74

**Comment by swashbuck** [comment]
> It should always happen. Not including an import or not noticing that eslint isn't working or not developing a plugin in a way that allows eslint to work is a little unacceptable. Those tools are there for a reason.

Yep, in my case, it was overlooked because the plugin just...worked. When I went back to fix it, I did see that the broken Adapt reference was highlighted as an error.

> As there always has been a reasonable alternative to exposing the window.Adapt in require('core/js/adapt') may I suggest that we just remove this code entirely?

I'm fine with removing it entirely, but not sure what others think?

**Comment by chris-steele** [comment]
@swashbuck I find this variable a time and wrist saver when debugging. I would prefer to see exposing this variable as a configurable option (that defaults to not exposed).

**Comment by oliverfoster** [comment]
Can you just do it when the dev tools is activated? At least then there's more chance of a bug being found.

**Comment by chris-steele** [comment]
Yes that makes most sense+convenience, would you agree @swashbuck?

**Comment by swashbuck** [comment]
> Can you just do it when the dev tools is activated rather than enabled? At least then there's more chance of a bug being found.

@oliverfoster What do you mean by "activated"? Do you mean when the Dev Tools drawer is open?

**Comment by oliverfoster** [comment]
Yeas. Unless you have a better idea?

**Comment by swashbuck** [comment]
That sounds good. I can work on this.

I also just noticed that this [line](https://github.com/cgkineo/adapt-devtools/blob/4a6152c0f82a2cadf0e57e005a2635d3bdd9ea7b/README.md?plain=1#L99C42-L99C50) needs to be removed/amended in the readme as it's not accurate.

> The core Adapt object can be reached via **window.a** for convenience.

**Comment by oliverfoster** [comment]
If you look through the history of the window.Adapt line you'll see it used to be window.a
