### ISSUE TITLE
"Complete page" button not accounting for items

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-devtools#89]
### Subject of the issue
In https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/221, the progress of presentation components with items are shown incrementally. That is, if 1 of 3 Narrative stages are completed, the PLP progress bar for the component will be 33% full.

This is breaking the "Complete page" option in Dev Tools. Presentation components with items are not shown in the PLP drawer as being fully completed. However, it _does_ appear that the overall page is marked as completed.

### Your environment
* PLP 7.7.0
* Dev Tools 3.5.4

### Steps to reproduce
1. In the vanilla p101 build, go to Presentation Components
2. Open the Dev Tools drawer and select "Complete page"

### Result
Components with items (e.g. Narrative) are shown as partially complete.

<img src="https://github.com/cgkineo/adapt-devtools/assets/898168/815e9346-ecd4-489b-b701-9ad5f87f4e86" width="350" alt="PLP">

**Comment by oliverfoster** [comment]
Can you fix this in plp please?

It should be 100 if the component is complete and otherwise return the items calculation. That's my fault. Apologies.

**Comment by swashbuck** [comment]
> Can you fix this in plp please?

Created https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/issues/228
